### ISSUE TITLE
hdiutil fixed

### ISSUE THREAD

**Issue by TRANTUAN-PC** [mast3rz3ro/SSHRD_Script_Lite#1]
line 189: 		hdiutil resize -sectors min "$temp_folder"'/ramdisk.dmg'
line 201 to 208:                        if [ "$platform" = 'Darwin' ] && [ "$check_ios" -ge '161' ]; then
	
		echo '[-] Packing using img4 utility ...'
		"$img4" -i "$temp_folder"'/reassigned_ramdisk.dmg' -o "$output_folder"'/ramdisk.img4' -M "$shsh_file" -A -T rdsk
                        else
                                                "$img4" -i "$temp_folder"'/ramdisk.dmg' -o "$output_folder"'/ramdisk.img4' -M "$shsh_file" -A -T rdsk
		
	fi

**Comment by mast3rz3ro** [comment]
Hi,

I have reset the header to intial and pushed some changes, please run it again and if error still presents then feel free to send a pull request with minimum changes.

**Comment by TRANTUAN-PC** [comment]
Ok,bro.
