### ISSUE TITLE
PZB in Darwin cannot write output to another directory

### ISSUE THREAD

**Issue by zygame110119** [mast3rz3ro/SSHRD_Script_Lite#11]
download succeeded
[!] PZB in Darwin cannot write output to another directory
[-] Moving downloaded files into: 1_prepare_ramdisk
[!] Checking downloaded files...
[e] File is missing: 1_prepare_ramdisk/DeviceTree.j71ap.im4p
j71ap.im4p

**Comment by zygame110119** [comment]
[-] START:iFirmware-Parser
[-] Parsing device info (from firmwares.json)...
[-] Parsing... filenames
[!] Checking the firmware_keys: misc/firmware_keys/iPad4,1_14G60.json
[!] Using the firmware_keys: misc/firmware_keys/iPad4,1_14G60.json
[-] Parsing... decryption_keys
[!] Start downloading the ramdisk files...
[!] Downloading into: 1_prepare_ramdisk/DeviceTree.j71ap.im4p
j71ap.im4p
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios10.3.3/091-23378-20170719-CA983C78-6977-11E7-8922-3D9100BA0AE3/iPad_64bit_10.3.3_14G60_Restore.ipsw
init done
Error: file Firmware/all_flash/DeviceTree.j71ap.im4p
j71ap.im4p does not exist, or is a directory
[!] Downloading into: 1_prepare_ramdisk/058-75094-062.dmg.trustcache
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios10.3.3/091-23378-20170719-CA983C78-6977-11E7-8922-3D9100BA0AE3/iPad_64bit_10.3.3_14G60_Restore.ipsw
init done
Error: file Firmware/058-75094-062.dmg.trustcache does not exist, or is a directory
[!] Downloading into: 1_prepare_ramdisk/kernelcache.release.ipad4
kernelcache.release.ipad4b
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios10.3.3/091-23378-20170719-CA983C78-6977-11E7-8922-3D9100BA0AE3/iPad_64bit_10.3.3_14G60_Restore.ipsw
init done
Error: file kernelcache.release.ipad4
kernelcache.release.ipad4b does not exist, or is a directory
[!] PZB in Darwin cannot write output to another directory
[-] Moving downloaded files into: 1_prepare_ramdisk
[!] Checking downloaded files...
[e] File is missing: 1_prepare_ramdisk/DeviceTree.j71ap.im4p
j71ap.im4p

**Comment by zygame110119** [comment]
zygame@zygamedeiMac-Pro SSHRD_Script_Lite % sudo ./sshrd_lite.sh -p iPad4,1 -b 14G60 -y 2
[-] START:iFirmware-Parser
[-] Parsing device info (from firmwares.json)...
[-] Parsing... filenames
[!] Checking the firmware_keys: misc/firmware_keys/iPad4,1_14G60.json
[!] Using the firmware_keys: misc/firmware_keys/iPad4,1_14G60.json
[-] Parsing... decryption_keys
[!] Start downloading the ramdisk files...
[!] Downloading into: 1_prepare_ramdisk/DeviceTree.j71ap.im4p
j71ap.im4p
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios10.3.3/091-23378-20170719-CA983C78-6977-11E7-8922-3D9100BA0AE3/iPad_64bit_10.3.3_14G60_Restore.ipsw
init done
Error: file Firmware/all_flash/DeviceTree.j71ap.im4p
j71ap.im4p does not exist, or is a directory
[!] Downloading into: 1_prepare_ramdisk/058-75094-062.dmg.trustcache
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios10.3.3/091-23378-20170719-CA983C78-6977-11E7-8922-3D9100BA0AE3/iPad_64bit_10.3.3_14G60_Restore.ipsw
init done
Error: file Firmware/058-75094-062.dmg.trustcache does not exist, or is a directory
[!] Downloading into: 1_prepare_ramdisk/kernelcache.release.ipad4
kernelcache.release.ipad4b
Version: 9bfdde2b2456181045f74631683fba491d8bf4f2 - 38
libfragmentzip version: 0.64-aaf6fae83a0aa6f7aae1c94721857076d04a14e8-RELEASE
init pzb: http://appldnld.apple.com/ios10.3.3/091-23378-20170719-CA983C78-6977-11E7-8922-3D9100BA0AE3/iPad_64bit_10.3.3_14G60_Restore.ipsw
init done
Error: file kernelcache.release.ipad4
kernelcache.release.ipad4b does not exist, or is a directory
[!] PZB in Darwin cannot write output to another directory
[-] Moving downloaded files into: 1_prepare_ramdisk
[!] Checking downloaded files...
[e] File is missing: 1_prepare_ramdisk/DeviceTree.j71ap.im4p
j71ap.im4p

**Comment by mast3rz3ro** [comment]
Hi there,

This error are encountering because the filenames are getting incorrectly parsed. I'm going to try fix this  soon.
 
https://github.com/mast3rz3ro/SSHRD_Script_Lite/issues/9

**Comment by zygame110119** [comment]
Nice, that's awesome, thanks very much.











---Original---
From: ***@***.***&gt;
Date: Thu, Sep 12, 2024 19:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mast3rz3ro/SSHRD_Script_Lite] PZB in Darwin cannot write outputto another directory (Issue #11)




 
Hi there,
 
This error are encountering because the filenames are getting incorrectly parsed. I'm going to try fix this  soon.
 
#9

**Comment by mast3rz3ro** [comment]
@zygame110119 

Hi, the issue should now be fixed but I'm not sure If it's gone work on the build version that you have chosen. I'm going to close this issue now, but feel free to open another issue in the future.
