### ISSUE TITLE
-p iPhone8,1 -s 15.6 can not boot into ssh mode

### ISSUE THREAD

**Issue by planktonwhc** [mast3rz3ro/SSHRD_Script_Lite#3]
phone only show progress bar logo, and didnt entered sshramdisk

**Comment by TRANTUAN-PC** [comment]
edit line 53 in sshrd_boot.sh to if [ ! -s "$bootchain"'/trustcache.img4' ]  [ "$cpid" = '0x8012' ]; then

**Comment by mast3rz3ro** [comment]
Fixed in: [1fde6d9](https://github.com/mast3rz3ro/SSHRD_Script_Lite/commit/1fde6d90a70f721ee3110c22219a1925a3279a75)
Thanks [TRANTUAN-PC](https://github.com/TRANTUAN-PC) for the last two commits.
