### ISSUE TITLE
iPhone7,1 （ios12） Production failed

### ISSUE THREAD

**Issue by zhuang2022** [mast3rz3ro/SSHRD_Script_Lite#9]
download succeeded
[!] PZB in Darwin cannot write output to another directory
[-] Moving downloaded files into: 1_prepare_ramdisk
[!] Checking downloaded files...
[e] File is missing: 1_prepare_ramdisk/DeviceTree.n56ap.im4p
n56ap.im4p

**Comment by chrismichaelmonaghan** [comment]
Im having the same issue.
